0,NameError,name 'factor' is not defined,0,,2023-05-23 21:32:12.696847,"[('factor', 3)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_16802/3742982240.py"", line 3, in <module>', '    factor', ""NameError: name 'factor' is not defined""]"
1,TypeError,unsupported operand type(s) for +: 'NoneType' and 'int',0,,2023-05-23 21:47:22.085022,"[('print_number_five_output + 2', 2)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_16802/55797484.py"", line 2, in <module>', '    print_number_five_output + 2', ""TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'""]"
